namespace PicCaptionr.Models;

/// <summary>
/// Represents the response from the AI API.
/// </summary>
public record AIResponse(

	/// <summary>
	/// Gets or sets the content of the response.
	/// </summary>
	string RawContent,

	/// <summary> 
	/// Gets or sets the formatted content of the response.
	/// </summary>
	string FormattedContent,

	/// <summary>
	/// Gets or sets the number of input tokens used in the request.
	/// </summary>
	int InputTokens,

	/// <summary>
	/// Gets or sets the number of output tokens generated by the AI.
	/// </summary>
	int OutputTokens);
