name: Build WPF App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate version
        id: version
        shell: bash
        run: |
          VERSION="1.0.0-preview.$(date +%y%m%d%H%M)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/PicCaptionr.WPFApp/PicCaptionr.WPFApp.csproj

      - name: Publish WPF App (Single EXE)
        run: dotnet publish src/PicCaptionr.WPFApp/PicCaptionr.WPFApp.csproj `
              -c Release `
              -r win-x64 `
              -p:PublishSingleFile=true `
              -p:PublishTrimmed=false `
              -p:IncludeNativeLibrariesForSelfExtract=true `
              -p:SelfContained=true `
              -p:DebugType=None `
              -o publish `
              /p:Version=${{ env.VERSION }}

      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PicCaptionr-WPF-${{ env.VERSION }}
          path: publish